Add Playback speed preference to Home screen video
eggheadio/egghead-next pull request #484
Opened 2021-03-01 18:26 UTC by zacjones93

This was surprisingly easy!

![image](https://user-images.githubusercontent.com/6188161/109539732-a6a9f400-7a8f-11eb-82de-72916cf32e4b.png)

![](https://media0.giphy.com/media/eoVusT7Pi9ODe/200.gif?cid=5a38a5a2gs9q31xjstv8hdprhpwey6fqsem6rc0k0hd4ror5&rid=200.gif)

2021-03-01 18:30 UTC, zacjones93 commented on src/components/pages/home/index.tsx
> +import {useEggheadPlayerPrefs} from 'components/EggheadPlayer/use-egghead-player'
We have a hook for PlayerPrefs!

2021-03-01 18:30 UTC, zacjones93 commented on src/components/pages/home/index.tsx
> +  const {setPlayerPrefs, playbackRate} = useEggheadPlayerPrefs()
grab relevant items

2021-03-01 18:30 UTC, zacjones93 commented on src/components/pages/home/index.tsx
> +                playbackRate={playbackRate}
pass playbackRate in

2021-03-01 18:30 UTC, zacjones93 commented on src/components/pages/home/index.tsx
> +                  setPlayerPrefs({playbackRate: rate})
set playbackRate when user would like to

2021-03-01 20:29 UTC, joelhooks requested changes
visually this isn't acceptable for presentation on the home page. The additional control bar has a specific intent on video pages that may not be present on the home page. 

imo, we'd be better off making this a clickable image that **navigates the user to the video resource page** and starts playing the video instead of tuning an inline viewing experience for this particular use case

2021-03-02 12:36 UTC, vojtaholik commented
another possible option would be to enable bitmovin's default (limited) speed controls for this use case (https://github.com/eggheadio/egghead-next/blob/main/src/components/EggheadPlayer/players/Bitmovin.js#L23)

2021-03-10 23:11 UTC, joelhooks commented
@zacjones93 what does this look like now?

2021-03-10 23:12 UTC, joelhooks approved these changes

2021-03-11 15:42 UTC, zacjones93 commented
Reverted the style to what it was previously, now the player itself has an option in settings to update speed

![Build the portfolio you need to be a badass web developer   egghead io](https://user-images.githubusercontent.com/6188161/110813343-69dfb900-8256-11eb-85a4-ea5465694aa6.png)

2021-03-11 15:50 UTC, theianjones requested changes
> we'd be better off making this a clickable image that navigates the user to the video resource page

I agree with Joel that this should be a clickable image that pushes them to the resource page. Talks like this have slides that you want to read and the experience of watching it in such a small frame is poor

2021-03-11 15:59 UTC, joelhooks commented
It'd give us a chance to create a "nice" poster frame. I'm strongly in favor of it over a special variant of the player inline.


The only advantage I can see to inline would be if we allowed it to autoplay (muted) for attention. That's a can of worms though.

2021-04-01 07:29 UTC, DrShpongle commented
@zacjones93  Is any help needed here?

2021-04-06 20:48 UTC, zacjones93 commented
Updating #533 to use an image

2021-04-06 20:48 UTC, closed without merging