Hiroko's name was being exported as Hiro
eggheadio/egghead-next pull request #690
Opened 2021-06-11 20:10 UTC by lsminter

There was a bug where Hiro had two names, Hiro and Hiroko. If you search for Hiro, three lessons would should up, if you searched for Hiroko, all of her lessons would show up. 

![Screen Shot 2021-06-11 at 11 43 02 AM](https://user-images.githubusercontent.com/26470581/121742919-5d693780-cab5-11eb-99b7-78dfb20489f9.png)

![Screen Shot 2021-06-11 at 12 00 13 PM](https://user-images.githubusercontent.com/26470581/121742922-5e9a6480-cab5-11eb-8ea3-4058331a5012.png)

In `egghead-next/src/components/search/instructors/index.tsx`, Hiroko's name was being exported as `hiro` instead of `hiroko` and I believe that's why these were showing up. 

![Screen Shot 2021-06-11 at 1 08 47 PM](https://user-images.githubusercontent.com/26470581/121743417-2c3d3700-cab6-11eb-974f-f99f3069438d.png)

After changing the name, nothing shows up after searching for `hiro`.

2021-06-11 20:11 UTC, lsminter commented on src/components/search/instructors/index.tsx
> +  'hiroko-nishimura': SearchHirokoNishimura,
Just this small change.

2021-06-14 17:50 UTC, zacjones93 commented
This looks great, we need to be consistent. 

The slug in the instructor page data needs to be updated as well

https://github.com/eggheadio/egghead-next/blob/main/src/components/search/instructors/hiroko-nishimura/hiroko-nishimura-page-data.ts#L8

2021-06-14 17:53 UTC, zacjones93 requested changes
This looks great, we need to be consistent.

The slug in the instructor page data needs to be updated as well

https://github.com/eggheadio/egghead-next/blob/main/src/components/search/instructors/hiroko-nishimura/hiroko-nishimura-page-data.ts#L8

Also, it's company policy for all PR's to include a GIF.

2021-06-14 19:15 UTC, lsminter commented on src/components/search/instructors/hiroko-nishimura/hiroko-nishimura-page-data.ts
> +    slug: 'resources-by-hiroko-nishimura',
Completely missed this one. Thanks Zac.

2021-06-15 15:16 UTC, zacjones93 approved these changes

2021-06-15 15:23 UTC, merged