Curated Hiroko's instructor page
eggheadio/egghead-next pull request #707
Opened 2021-06-21 19:47 UTC by lsminter

![](https://media4.giphy.com/media/1hqYk0leUMddBBkAM7/200w.gif?cid=5a38a5a24t1nwozc8vp9rwktewa5c09a1799xl17k4jgmru8&rid=200w.gif&ct=g)

I'm really happy with how this turned out! It felt good to be able to do this pretty much on my own. Using sanity really made this easy. 

![Screen Shot 2021-06-21 at 12 40 25 PM](https://user-images.githubusercontent.com/26470581/122818840-885e4300-d28e-11eb-9f31-49a4b0c9a7d8.png)

Hiroko has two courses on egghead and wrote her own eBook that I added to her instructor page.

2021-06-21 20:11 UTC, dealingwith commented
This probably isn't specific to this page, but in light mode this card effect makes the text hard to read

<img width="462" alt="Screen Shot 2021-06-21 at 3 10 48 PM" src="https://user-images.githubusercontent.com/124208/122821859-fa408780-d2a2-11eb-80d2-26c90a3f0b2a.png">

2021-06-21 20:12 UTC, dealingwith commented
@vojtaholik see above

Otherwise this LGTM

2021-06-21 21:37 UTC, zacjones93 requested changes

2021-06-21 21:37 UTC, zacjones93 commented on src/components/search/instructors/hiroko-nishimura/index.tsx
> +                      track('clicked jumbotron resource', {
this track link is inconsistent with the `eventName` above on line 77
```suggestion
                      track('clicked Hiroko Nishimura instructor page CTA', {
```

2021-06-21 21:37 UTC, zacjones93 commented on src/components/search/instructors/hiroko-nishimura/index.tsx
> +                      track('clicked jumbotron resource', {
```suggestion
                      track('clicked Hiroko Nishimura instructor page CTA', {
```

2021-06-21 21:37 UTC, zacjones93 commented on src/components/search/instructors/hiroko-nishimura/index.tsx
> +const FeaturedCourse: React.FC<{location: string; resource: any}> = ({
@dealingwith this page uses a one-off component so those darkmode style issues should be isolated to this page.

@lsminter here's an example of how to fix this
https://github.com/eggheadio/egghead-next/blob/main/src/components/search/instructors/stephanie-eckles/index.tsx#L186-L206

2021-06-23 17:56 UTC, lsminter commented
@zacjones93 I believe I've done all of your suggested updates. @dealingwith Can you guys double check to make sure this works?

2021-06-24 01:11 UTC, dealingwith commented
Card still has issues in light mode.

<img width="470" alt="Screen Shot 2021-06-23 at 8 10 43 PM" src="https://user-images.githubusercontent.com/124208/123187122-243ea900-d45f-11eb-9d33-2607ad65ce8c.png">

2021-06-28 21:04 UTC, zacjones93 commented
Went ahead and got that fixed @lsminter @dealingwith 

![Image 2021-06-28 at 5 02 37 PM](https://user-images.githubusercontent.com/6188161/123703781-d8ab4700-d832-11eb-8d47-25dbeb7b350f.png)
![Image 2021-06-28 at 5 02 46 PM](https://user-images.githubusercontent.com/6188161/123703790-dc3ece00-d832-11eb-9fa1-5fcfab69f0e1.png)

2021-07-02 19:36 UTC, zacjones93 approved these changes

2021-07-02 19:47 UTC, merged